apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: jbdiop/event-bus
